; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!


[Setup]
AppName=Northside EMS System
AppVersion=1.0
DefaultDirName={pf}\NorthsideEMS

[Files]
Source: "YourAppExecutable.exe"; DestDir: "{app}"
Source: "YourDatabase.sqlite"; DestDir: "{app}"

[Run]
Filename: "{app}\YourAppExecutable.exe"; Description: "Run My Application"; Flags: postinstall nowait